import type { Emt, Hospital, Location, Unit } from "./types";

export const LOCATIONS: Location[] = [
  {
    "name": "Namumira–Bukasa Level Crossing, Katosi Rd, Mukono",
    "region": "Central",
    "lat": 0.3532,
    "lng": 32.755
  },
  {
    "name": "Mukono Town Centre",
    "region": "Central",
    "lat": 0.3533,
    "lng": 32.7553
  },
  {
    "name": "Kampala–Jinja Highway, Seeta",
    "region": "Central",
    "lat": 0.339,
    "lng": 32.742
  },
  {
    "name": "Kampala Northern Bypass, Kyaliwajjala",
    "region": "Central",
    "lat": 0.376,
    "lng": 32.65
  },
  {
    "name": "Kampala City Centre",
    "region": "Central",
    "lat": 0.3136,
    "lng": 32.5811
  },
  {
    "name": "Entebbe Road, Kajjansi",
    "region": "Central",
    "lat": 0.152,
    "lng": 32.549
  },
  {
    "name": "Masaka Town, Kampala–Mbarara Highway",
    "region": "Central",
    "lat": -0.3333,
    "lng": 31.7333
  },
  {
    "name": "Kayunga Town Centre",
    "region": "Central",
    "lat": 0.7061,
    "lng": 32.8853
  },
  {
    "name": "Mubende Town Centre",
    "region": "Central",
    "lat": 0.5636,
    "lng": 31.3894
  },
  {
    "name": "Jinja Town, Kampala–Jinja Highway",
    "region": "Eastern",
    "lat": 0.4479,
    "lng": 33.2026
  },
  {
    "name": "Mbale Town Centre",
    "region": "Eastern",
    "lat": 1.0827,
    "lng": 34.1751
  },
  {
    "name": "Tororo Town, Malaba Border Road",
    "region": "Eastern",
    "lat": 0.6928,
    "lng": 34.1809
  },
  {
    "name": "Soroti Town Centre",
    "region": "Eastern",
    "lat": 1.7146,
    "lng": 33.6111
  },
  {
    "name": "Gulu Town Centre",
    "region": "Northern",
    "lat": 2.7747,
    "lng": 32.299
  },
  {
    "name": "Lira Town Centre",
    "region": "Northern",
    "lat": 2.235,
    "lng": 32.9096
  },
  {
    "name": "Arua Town Centre",
    "region": "Northern",
    "lat": 3.0201,
    "lng": 30.9109
  },
  {
    "name": "Kitgum Town Centre",
    "region": "Northern",
    "lat": 3.2833,
    "lng": 32.8833
  },
  {
    "name": "Moroto Town Centre",
    "region": "Northern",
    "lat": 2.5361,
    "lng": 34.6656
  },
  {
    "name": "Mbarara City Centre",
    "region": "Western",
    "lat": -0.6072,
    "lng": 30.6545
  },
  {
    "name": "Fort Portal City Centre",
    "region": "Western",
    "lat": 0.671,
    "lng": 30.2748
  },
  {
    "name": "Kabale Town Centre",
    "region": "Western",
    "lat": -1.2486,
    "lng": 29.9853
  },
  {
    "name": "Hoima City Centre",
    "region": "Western",
    "lat": 1.4356,
    "lng": 31.3518
  }
];

export const INITIAL_UNITS: Unit[] = [
  {
    "id": "AMB-01",
    "type": "Ambulance",
    "agency": "Uganda Red Cross Society — Mukono Highway Unit",
    "country": "Uganda",
    "region": "Central",
    "zone": "Mukono Town Centre",
    "lat": 0.348,
    "lng": 32.748,
    "status": "available",
    "capacity": 4,
    "phone": "+256 760 588 189",
    "assignedIncident": null
  },
  {
    "id": "AMB-02",
    "type": "Ambulance",
    "agency": "Ministry of Health National Ambulance Service — Mukono Constituency Unit",
    "country": "Uganda",
    "region": "Central",
    "zone": "Mukono Town Centre",
    "lat": 0.36,
    "lng": 32.76,
    "status": "available",
    "capacity": 4,
    "phone": "912",
    "assignedIncident": null
  },
  {
    "id": "AMB-03",
    "type": "Ambulance",
    "agency": "Uganda Red Cross Society — Kampala HQ Unit",
    "country": "Uganda",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.32,
    "lng": 32.585,
    "status": "available",
    "capacity": 4,
    "phone": "+256 760 588 189",
    "assignedIncident": null
  },
  {
    "id": "AMB-11",
    "type": "Ambulance",
    "agency": "St John Ambulance Uganda — Kampala HQ",
    "country": "Uganda",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.316,
    "lng": 32.583,
    "status": "available",
    "capacity": 4,
    "phone": "+256 414 230 671",
    "assignedIncident": null
  },
  {
    "id": "AMB-12",
    "type": "Ambulance",
    "agency": "International Medical Group (IMG) Emergency Ambulance",
    "country": "Uganda",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.31,
    "lng": 32.59,
    "status": "available",
    "capacity": 4,
    "phone": "+256 312 200 400",
    "assignedIncident": null
  },
  {
    "id": "AMB-13",
    "type": "Ambulance",
    "agency": "Case Medical Centre Ambulance",
    "country": "Uganda",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.3244,
    "lng": 32.575,
    "status": "available",
    "capacity": 4,
    "phone": "+256 414 250 362",
    "assignedIncident": null
  },
  {
    "id": "POL-11",
    "type": "Police",
    "agency": "Uganda Police Force — Mukono Div.",
    "country": "Uganda",
    "region": "Central",
    "zone": "Mukono Town Centre",
    "lat": 0.355,
    "lng": 32.75,
    "status": "available",
    "capacity": 99,
    "phone": "999 / 112",
    "assignedIncident": null
  },
  {
    "id": "POL-12",
    "type": "Police",
    "agency": "Uganda Police Force — Kampala Metro",
    "country": "Uganda",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.365,
    "lng": 32.655,
    "status": "available",
    "capacity": 99,
    "phone": "999 / 112",
    "assignedIncident": null
  },
  {
    "id": "AMB-04",
    "type": "Ambulance",
    "agency": "St. Francis Hospital Nsambya (Outreach)",
    "country": "Uganda",
    "region": "Central",
    "zone": "Entebbe Road, Kajjansi",
    "lat": 0.16,
    "lng": 32.555,
    "status": "available",
    "capacity": 4,
    "phone": "+256 414 267 012",
    "assignedIncident": null
  },
  {
    "id": "AMB-05",
    "type": "Ambulance",
    "agency": "Uganda Red Cross Society — Eastern Region",
    "country": "Uganda",
    "region": "Eastern",
    "zone": "Jinja Town, Kampala–Jinja Highway",
    "lat": 0.45,
    "lng": 33.205,
    "status": "available",
    "capacity": 4,
    "phone": "+256 760 588 189",
    "assignedIncident": null
  },
  {
    "id": "POL-13",
    "type": "Police",
    "agency": "Uganda Police Force — Jinja Div.",
    "country": "Uganda",
    "region": "Eastern",
    "zone": "Jinja Town, Kampala–Jinja Highway",
    "lat": 0.446,
    "lng": 33.2,
    "status": "available",
    "capacity": 99,
    "phone": "999 / 112",
    "assignedIncident": null
  },
  {
    "id": "AMB-06",
    "type": "Ambulance",
    "agency": "Ministry of Health National Ambulance Service — Mbale Constituency Unit",
    "country": "Uganda",
    "region": "Eastern",
    "zone": "Mbale Town Centre",
    "lat": 1.08,
    "lng": 34.172,
    "status": "available",
    "capacity": 4,
    "phone": "912",
    "assignedIncident": null
  },
  {
    "id": "AMB-14",
    "type": "Ambulance",
    "agency": "Ministry of Health National Ambulance Service — Soroti Constituency Unit",
    "country": "Uganda",
    "region": "Eastern",
    "zone": "Soroti Town Centre",
    "lat": 1.712,
    "lng": 33.608,
    "status": "available",
    "capacity": 4,
    "phone": "912",
    "assignedIncident": null
  },
  {
    "id": "POL-16",
    "type": "Police",
    "agency": "Uganda Police Force — Mbale Div.",
    "country": "Uganda",
    "region": "Eastern",
    "zone": "Mbale Town Centre",
    "lat": 1.085,
    "lng": 34.177,
    "status": "available",
    "capacity": 99,
    "phone": "999 / 112",
    "assignedIncident": null
  },
  {
    "id": "AMB-07",
    "type": "Ambulance",
    "agency": "Ministry of Health National Ambulance Service — Gulu Constituency Unit",
    "country": "Uganda",
    "region": "Northern",
    "zone": "Gulu Town Centre",
    "lat": 2.772,
    "lng": 32.301,
    "status": "available",
    "capacity": 4,
    "phone": "912",
    "assignedIncident": null
  },
  {
    "id": "POL-14",
    "type": "Police",
    "agency": "Uganda Police Force — Gulu Div.",
    "country": "Uganda",
    "region": "Northern",
    "zone": "Gulu Town Centre",
    "lat": 2.777,
    "lng": 32.296,
    "status": "available",
    "capacity": 99,
    "phone": "999 / 112",
    "assignedIncident": null
  },
  {
    "id": "AMB-08",
    "type": "Ambulance",
    "agency": "Ministry of Health National Ambulance Service — Lira Constituency Unit",
    "country": "Uganda",
    "region": "Northern",
    "zone": "Lira Town Centre",
    "lat": 2.237,
    "lng": 32.907,
    "status": "available",
    "capacity": 4,
    "phone": "912",
    "assignedIncident": null
  },
  {
    "id": "AMB-15",
    "type": "Ambulance",
    "agency": "Uganda Red Cross Society — Arua",
    "country": "Uganda",
    "region": "Northern",
    "zone": "Arua Town Centre",
    "lat": 3.018,
    "lng": 30.913,
    "status": "available",
    "capacity": 4,
    "phone": "+256 760 588 189",
    "assignedIncident": null
  },
  {
    "id": "AMB-16",
    "type": "Ambulance",
    "agency": "Ministry of Health National Ambulance Service — Moroto Constituency Unit",
    "country": "Uganda",
    "region": "Northern",
    "zone": "Moroto Town Centre",
    "lat": 2.534,
    "lng": 34.663,
    "status": "available",
    "capacity": 4,
    "phone": "912",
    "assignedIncident": null
  },
  {
    "id": "AMB-09",
    "type": "Ambulance",
    "agency": "Ministry of Health National Ambulance Service — Mbarara Constituency Unit",
    "country": "Uganda",
    "region": "Western",
    "zone": "Mbarara City Centre",
    "lat": -0.605,
    "lng": 30.657,
    "status": "available",
    "capacity": 4,
    "phone": "912",
    "assignedIncident": null
  },
  {
    "id": "POL-15",
    "type": "Police",
    "agency": "Uganda Police Force — Mbarara Div.",
    "country": "Uganda",
    "region": "Western",
    "zone": "Mbarara City Centre",
    "lat": -0.609,
    "lng": 30.652,
    "status": "available",
    "capacity": 99,
    "phone": "999 / 112",
    "assignedIncident": null
  },
  {
    "id": "AMB-10",
    "type": "Ambulance",
    "agency": "Ministry of Health National Ambulance Service — Fort Portal Constituency Unit",
    "country": "Uganda",
    "region": "Western",
    "zone": "Fort Portal City Centre",
    "lat": 0.673,
    "lng": 30.277,
    "status": "available",
    "capacity": 4,
    "phone": "912",
    "assignedIncident": null
  },
  {
    "id": "AMB-17",
    "type": "Ambulance",
    "agency": "St John Ambulance Uganda — Kasese Station",
    "country": "Uganda",
    "region": "Western",
    "zone": "Fort Portal City Centre",
    "lat": 0.669,
    "lng": 30.27,
    "status": "available",
    "capacity": 4,
    "phone": "+256 414 230 671",
    "assignedIncident": null
  },
  {
    "id": "AMB-18",
    "type": "Ambulance",
    "agency": "Uganda Red Cross Society — Kabale",
    "country": "Uganda",
    "region": "Western",
    "zone": "Kabale Town Centre",
    "lat": -1.246,
    "lng": 29.988,
    "status": "available",
    "capacity": 4,
    "phone": "+256 760 588 189",
    "assignedIncident": null
  },
  {
    "id": "AMB-19",
    "type": "Ambulance",
    "agency": "Ministry of Health National Ambulance Service — Hoima Constituency Unit",
    "country": "Uganda",
    "region": "Western",
    "zone": "Hoima City Centre",
    "lat": 1.433,
    "lng": 31.354,
    "status": "available",
    "capacity": 4,
    "phone": "912",
    "assignedIncident": null
  },
  {
    "id": "FIRE-01",
    "type": "Fire",
    "agency": "Uganda Police Fire Prevention & Rescue Services — Kampala Station",
    "country": "Uganda",
    "region": "Central",
    "zone": "Queen's Way, Kampala",
    "lat": 0.307893,
    "lng": 32.577632,
    "status": "available",
    "capacity": 99,
    "phone": "0800 121 222",
    "assignedIncident": null
  },
  {
    "id": "FIRE-02",
    "type": "Fire",
    "agency": "Uganda Police Fire Prevention & Rescue Services — Entebbe Station",
    "country": "Uganda",
    "region": "Central",
    "zone": "Entebbe",
    "lat": 0.0512,
    "lng": 32.4637,
    "status": "available",
    "capacity": 99,
    "phone": "999 / 112",
    "assignedIncident": null
  },
  {
    "id": "FIRE-03",
    "type": "Fire",
    "agency": "Uganda Police Fire Prevention & Rescue Services — Masaka Station",
    "country": "Uganda",
    "region": "Central",
    "zone": "Masaka Town, Kampala–Mbarara Highway",
    "lat": -0.334,
    "lng": 31.734,
    "status": "available",
    "capacity": 99,
    "phone": "999 / 112",
    "assignedIncident": null
  },
  {
    "id": "FIRE-04",
    "type": "Fire",
    "agency": "Uganda Police Fire Prevention & Rescue Services — Jinja Station",
    "country": "Uganda",
    "region": "Eastern",
    "zone": "Jinja Town, Kampala–Jinja Highway",
    "lat": 0.447,
    "lng": 33.204,
    "status": "available",
    "capacity": 99,
    "phone": "999 / 112",
    "assignedIncident": null
  },
  {
    "id": "FIRE-05",
    "type": "Fire",
    "agency": "Uganda Police Fire Prevention & Rescue Services — Mbale Station",
    "country": "Uganda",
    "region": "Eastern",
    "zone": "Mbale Town Centre",
    "lat": 1.081,
    "lng": 34.176,
    "status": "available",
    "capacity": 99,
    "phone": "999 / 112",
    "assignedIncident": null
  },
  {
    "id": "FIRE-06",
    "type": "Fire",
    "agency": "Uganda Police Fire Prevention & Rescue Services — Tororo Station",
    "country": "Uganda",
    "region": "Eastern",
    "zone": "Tororo Town, Malaba Border Road",
    "lat": 0.692,
    "lng": 34.18,
    "status": "available",
    "capacity": 99,
    "phone": "999 / 112",
    "assignedIncident": null
  },
  {
    "id": "FIRE-07",
    "type": "Fire",
    "agency": "Uganda Police Fire Prevention & Rescue Services — Hoima Station",
    "country": "Uganda",
    "region": "Western",
    "zone": "Hoima City Centre",
    "lat": 1.435,
    "lng": 31.351,
    "status": "available",
    "capacity": 99,
    "phone": "999 / 112",
    "assignedIncident": null
  },
  {
    "id": "FIRE-08",
    "type": "Fire",
    "agency": "Uganda Police Fire Prevention & Rescue Services — Mbarara Station",
    "country": "Uganda",
    "region": "Western",
    "zone": "Mbarara City Centre",
    "lat": -0.606,
    "lng": 30.656,
    "status": "available",
    "capacity": 99,
    "phone": "999 / 112",
    "assignedIncident": null
  },
  {
    "id": "FIRE-P01",
    "type": "Fire",
    "agency": "Fire Masters Ltd (Private, 24-hr Fire Fighting)",
    "country": "Uganda",
    "region": "Central",
    "zone": "Kibuli, Kampala",
    "lat": 0.3005,
    "lng": 32.587,
    "status": "available",
    "capacity": 99,
    "phone": "+256 414 258 912",
    "assignedIncident": null
  },
  {
    "id": "FIRE-P02",
    "type": "Fire",
    "agency": "Fire Systems Ltd (Private Fire & Safety Solutions)",
    "country": "Uganda",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.315,
    "lng": 32.586,
    "status": "available",
    "capacity": 99,
    "phone": "+256 414 346 020",
    "assignedIncident": null
  },
  {
    "id": "FIRE-P03",
    "type": "Fire",
    "agency": "Civil Aviation Authority — Airport Rescue & Fire Fighting Service",
    "country": "Uganda",
    "region": "Central",
    "zone": "Entebbe International Airport",
    "lat": 0.0424,
    "lng": 32.4435,
    "status": "available",
    "capacity": 99,
    "phone": "+256 414 320 500",
    "assignedIncident": null
  },
  {
    "id": "AMB-EAC-01",
    "type": "Ambulance",
    "agency": "Flare / Rescue.co Emergency Dispatch Network",
    "country": "Kenya",
    "region": "Kenya",
    "zone": "Nairobi",
    "lat": -1.2921,
    "lng": 36.8219,
    "status": "available",
    "capacity": 4,
    "phone": "0714 911 911",
    "assignedIncident": null
  },
  {
    "id": "AMB-EAC-02",
    "type": "Ambulance",
    "agency": "AMREF Flying Doctors (Air Ambulance)",
    "country": "Kenya",
    "region": "Kenya",
    "zone": "Nairobi (Wilson Airport)",
    "lat": -1.3218,
    "lng": 36.8151,
    "status": "available",
    "capacity": 2,
    "phone": "+254 722 207 350",
    "assignedIncident": null
  },
  {
    "id": "AMB-EAC-03",
    "type": "Ambulance",
    "agency": "SAMU — Rwanda Biomedical Centre EMS Division",
    "country": "Rwanda",
    "region": "Rwanda",
    "zone": "Kigali",
    "lat": -1.9441,
    "lng": 30.0619,
    "status": "available",
    "capacity": 4,
    "phone": "912",
    "assignedIncident": null
  },
  {
    "id": "AMB-EAC-04",
    "type": "Ambulance",
    "agency": "Rwanda Red Cross EMS Ambulance",
    "country": "Rwanda",
    "region": "Rwanda",
    "zone": "Kigali",
    "lat": -1.95,
    "lng": 30.058,
    "status": "available",
    "capacity": 4,
    "phone": "+250 788 100 100",
    "assignedIncident": null
  },
  {
    "id": "AMB-EAC-05",
    "type": "Ambulance",
    "agency": "Tanzania Red Cross Society Ambulance Service",
    "country": "Tanzania",
    "region": "Tanzania",
    "zone": "Dar es Salaam",
    "lat": -6.7924,
    "lng": 39.2083,
    "status": "available",
    "capacity": 4,
    "phone": "+255 22 286 4382",
    "assignedIncident": null
  },
  {
    "id": "AMB-EAC-06",
    "type": "Ambulance",
    "agency": "Burundi Red Cross Ambulance Service",
    "country": "Burundi",
    "region": "Burundi",
    "zone": "Bujumbura",
    "lat": -3.3822,
    "lng": 29.3644,
    "status": "available",
    "capacity": 4,
    "phone": "+257 22 21 7643",
    "assignedIncident": null
  },
  {
    "id": "AMB-EAC-07",
    "type": "Ambulance",
    "agency": "Croix-Rouge de la RDC Ambulance Service",
    "country": "DR Congo",
    "region": "DR Congo",
    "zone": "Kinshasa",
    "lat": -4.3276,
    "lng": 15.3136,
    "status": "available",
    "capacity": 4,
    "phone": "+243 997 235 775",
    "assignedIncident": null
  },
  {
    "id": "AMB-EAC-08",
    "type": "Ambulance",
    "agency": "South Sudan Red Cross Ambulance Service",
    "country": "South Sudan",
    "region": "South Sudan",
    "zone": "Juba",
    "lat": 4.8517,
    "lng": 31.5825,
    "status": "available",
    "capacity": 4,
    "phone": "+211 912 000 000",
    "assignedIncident": null
  }
];

export const INITIAL_HOSPITALS: Hospital[] = [
  {
    "id": "HOSP-01",
    "name": "Mulago National Referral Hospital",
    "tier": "National Referral",
    "ownership": "Public",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.33778,
    "lng": 32.57556,
    "bedsTotal": 1200,
    "bedsAvailable": 410,
    "traumaTotal": 40,
    "traumaAvailable": 16,
    "phone": "+256 41 454 1589",
    "country": "Uganda"
  },
  {
    "id": "HOSP-02",
    "name": "Butabika National Referral Hospital (Mental Health)",
    "tier": "National Referral",
    "ownership": "Public",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.31583,
    "lng": 32.65917,
    "bedsTotal": 900,
    "bedsAvailable": 260,
    "traumaTotal": 3,
    "traumaAvailable": 1,
    "phone": "+256 414 504 388",
    "country": "Uganda"
  },
  {
    "id": "HOSP-03",
    "name": "China-Uganda Friendship Hospital, Naguru",
    "tier": "National Referral",
    "ownership": "Public",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.3423,
    "lng": 32.6094,
    "bedsTotal": 100,
    "bedsAvailable": 38,
    "traumaTotal": 8,
    "traumaAvailable": 4,
    "phone": "+256 41 234 5001",
    "country": "Uganda"
  },
  {
    "id": "HOSP-04",
    "name": "Kawempe National Referral Hospital",
    "tier": "National Referral",
    "ownership": "Public",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.36,
    "lng": 32.572,
    "bedsTotal": 200,
    "bedsAvailable": 70,
    "traumaTotal": 6,
    "traumaAvailable": 3,
    "phone": "+256 41 234 5002",
    "country": "Uganda"
  },
  {
    "id": "HOSP-05",
    "name": "Kiruddu National Referral Hospital",
    "tier": "National Referral",
    "ownership": "Public",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.287,
    "lng": 32.594,
    "bedsTotal": 240,
    "bedsAvailable": 85,
    "traumaTotal": 10,
    "traumaAvailable": 5,
    "phone": "+256 41 234 5003",
    "country": "Uganda"
  },
  {
    "id": "HOSP-06",
    "name": "Arua Regional Referral Hospital",
    "tier": "Regional Referral",
    "ownership": "Public",
    "region": "Northern",
    "zone": "Arua Town Centre",
    "lat": 3.01944,
    "lng": 30.9125,
    "bedsTotal": 272,
    "bedsAvailable": 95,
    "traumaTotal": 8,
    "traumaAvailable": 4,
    "phone": "+256 47 645 0012",
    "country": "Uganda"
  },
  {
    "id": "HOSP-07",
    "name": "Fort Portal Regional Referral Hospital (Buhinga)",
    "tier": "Regional Referral",
    "ownership": "Public",
    "region": "Western",
    "zone": "Fort Portal City Centre",
    "lat": 0.65528,
    "lng": 30.28139,
    "bedsTotal": 333,
    "bedsAvailable": 110,
    "traumaTotal": 7,
    "traumaAvailable": 3,
    "phone": "+256 48 342 2013",
    "country": "Uganda"
  },
  {
    "id": "HOSP-08",
    "name": "Gulu Regional Referral Hospital",
    "tier": "Regional Referral",
    "ownership": "Public",
    "region": "Northern",
    "zone": "Gulu Town Centre",
    "lat": 2.77,
    "lng": 32.302,
    "bedsTotal": 400,
    "bedsAvailable": 150,
    "traumaTotal": 9,
    "traumaAvailable": 5,
    "phone": "+256 47 143 2014",
    "country": "Uganda"
  },
  {
    "id": "HOSP-09",
    "name": "Hoima Regional Referral Hospital",
    "tier": "Regional Referral",
    "ownership": "Public",
    "region": "Western",
    "zone": "Hoima City Centre",
    "lat": 1.4356,
    "lng": 31.3518,
    "bedsTotal": 267,
    "bedsAvailable": 90,
    "traumaTotal": 6,
    "traumaAvailable": 3,
    "phone": "+256 46 544 0015",
    "country": "Uganda"
  },
  {
    "id": "HOSP-10",
    "name": "Jinja Regional Referral Hospital",
    "tier": "Regional Referral",
    "ownership": "Public",
    "region": "Eastern",
    "zone": "Jinja Town, Kampala–Jinja Highway",
    "lat": 0.443,
    "lng": 33.208,
    "bedsTotal": 500,
    "bedsAvailable": 190,
    "traumaTotal": 8,
    "traumaAvailable": 5,
    "phone": "+256 43 412 0016",
    "country": "Uganda"
  },
  {
    "id": "HOSP-11",
    "name": "Kabale Regional Referral Hospital",
    "tier": "Regional Referral",
    "ownership": "Public",
    "region": "Western",
    "zone": "Kabale Town Centre",
    "lat": -1.2486,
    "lng": 29.9853,
    "bedsTotal": 250,
    "bedsAvailable": 80,
    "traumaTotal": 5,
    "traumaAvailable": 2,
    "phone": "+256 48 642 2017",
    "country": "Uganda"
  },
  {
    "id": "HOSP-12",
    "name": "Kayunga Regional Referral Hospital",
    "tier": "Regional Referral",
    "ownership": "Public",
    "region": "Central",
    "zone": "Kayunga Town Centre",
    "lat": 0.7061,
    "lng": 32.8853,
    "bedsTotal": 100,
    "bedsAvailable": 35,
    "traumaTotal": 4,
    "traumaAvailable": 2,
    "phone": "+256 41 289 0018",
    "country": "Uganda"
  },
  {
    "id": "HOSP-13",
    "name": "Lira Regional Referral Hospital",
    "tier": "Regional Referral",
    "ownership": "Public",
    "region": "Northern",
    "zone": "Lira Town Centre",
    "lat": 2.239,
    "lng": 32.905,
    "bedsTotal": 280,
    "bedsAvailable": 95,
    "traumaTotal": 6,
    "traumaAvailable": 3,
    "phone": "+256 47 320 0019",
    "country": "Uganda"
  },
  {
    "id": "HOSP-14",
    "name": "Masaka Regional Referral Hospital",
    "tier": "Regional Referral",
    "ownership": "Public",
    "region": "Central",
    "zone": "Masaka Town, Kampala–Mbarara Highway",
    "lat": -0.3333,
    "lng": 31.7333,
    "bedsTotal": 300,
    "bedsAvailable": 105,
    "traumaTotal": 6,
    "traumaAvailable": 3,
    "phone": "+256 48 142 0020",
    "country": "Uganda"
  },
  {
    "id": "HOSP-15",
    "name": "Mbale Regional Referral Hospital",
    "tier": "Regional Referral",
    "ownership": "Public",
    "region": "Eastern",
    "zone": "Mbale Town Centre",
    "lat": 1.079,
    "lng": 34.178,
    "bedsTotal": 450,
    "bedsAvailable": 160,
    "traumaTotal": 7,
    "traumaAvailable": 4,
    "phone": "+256 45 433 3078",
    "country": "Uganda"
  },
  {
    "id": "HOSP-16",
    "name": "Mbarara Regional Referral Hospital",
    "tier": "Regional Referral",
    "ownership": "Public",
    "region": "Western",
    "zone": "Mbarara City Centre",
    "lat": -0.603,
    "lng": 30.659,
    "bedsTotal": 600,
    "bedsAvailable": 220,
    "traumaTotal": 10,
    "traumaAvailable": 6,
    "phone": "+256 48 542 0022",
    "country": "Uganda"
  },
  {
    "id": "HOSP-17",
    "name": "Moroto Regional Referral Hospital",
    "tier": "Regional Referral",
    "ownership": "Public",
    "region": "Northern",
    "zone": "Moroto Town Centre",
    "lat": 2.5361,
    "lng": 34.6656,
    "bedsTotal": 150,
    "bedsAvailable": 55,
    "traumaTotal": 4,
    "traumaAvailable": 2,
    "phone": "+256 47 745 0023",
    "country": "Uganda"
  },
  {
    "id": "HOSP-18",
    "name": "Mubende Regional Referral Hospital",
    "tier": "Regional Referral",
    "ownership": "Public",
    "region": "Central",
    "zone": "Mubende Town Centre",
    "lat": 0.5636,
    "lng": 31.3894,
    "bedsTotal": 200,
    "bedsAvailable": 70,
    "traumaTotal": 5,
    "traumaAvailable": 2,
    "phone": "+256 46 445 0024",
    "country": "Uganda"
  },
  {
    "id": "HOSP-19",
    "name": "Soroti Regional Referral Hospital",
    "tier": "Regional Referral",
    "ownership": "Public",
    "region": "Eastern",
    "zone": "Soroti Town Centre",
    "lat": 1.7146,
    "lng": 33.6111,
    "bedsTotal": 280,
    "bedsAvailable": 100,
    "traumaTotal": 6,
    "traumaAvailable": 3,
    "phone": "+256 45 561 0025",
    "country": "Uganda"
  },
  {
    "id": "HOSP-20",
    "name": "St. Francis Hospital Nsambya",
    "tier": "Private (PNFP)",
    "ownership": "Private not-for-profit",
    "region": "Central",
    "zone": "Entebbe Road, Kajjansi",
    "lat": 0.302,
    "lng": 32.573,
    "bedsTotal": 300,
    "bedsAvailable": 100,
    "traumaTotal": 6,
    "traumaAvailable": 3,
    "phone": "+256 414 267 012",
    "country": "Uganda"
  },
  {
    "id": "HOSP-21",
    "name": "Nakasero Hospital",
    "tier": "Private",
    "ownership": "Private, for-profit",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.32694,
    "lng": 32.57944,
    "bedsTotal": 100,
    "bedsAvailable": 35,
    "traumaTotal": 8,
    "traumaAvailable": 4,
    "phone": "+256 312 531 400",
    "country": "Uganda"
  },
  {
    "id": "HOSP-22",
    "name": "International Hospital Kampala (IHK)",
    "tier": "Private",
    "ownership": "Private, for-profit",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.30528,
    "lng": 32.61111,
    "bedsTotal": 100,
    "bedsAvailable": 32,
    "traumaTotal": 6,
    "traumaAvailable": 3,
    "phone": "+256 312 200 400",
    "country": "Uganda"
  },
  {
    "id": "HOSP-23",
    "name": "Case Medical Centre (Case Hospital)",
    "tier": "Private",
    "ownership": "Private, for-profit",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.3244,
    "lng": 32.575,
    "bedsTotal": 80,
    "bedsAvailable": 26,
    "traumaTotal": 5,
    "traumaAvailable": 2,
    "phone": "+256 414 250 362",
    "country": "Uganda"
  },
  {
    "id": "HOSP-24",
    "name": "Kampala Hospital",
    "tier": "Private",
    "ownership": "Private, for-profit",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.33306,
    "lng": 32.58444,
    "bedsTotal": 100,
    "bedsAvailable": 34,
    "traumaTotal": 5,
    "traumaAvailable": 2,
    "phone": "+256 312 236 400",
    "country": "Uganda"
  },
  {
    "id": "HOSP-25",
    "name": "Mengo Hospital",
    "tier": "Private (PNFP)",
    "ownership": "Private, non-profit",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.31278,
    "lng": 32.55833,
    "bedsTotal": 300,
    "bedsAvailable": 110,
    "traumaTotal": 7,
    "traumaAvailable": 3,
    "phone": "+256 414 270 222",
    "country": "Uganda"
  },
  {
    "id": "HOSP-26",
    "name": "Lubaga (Rubaga) Hospital",
    "tier": "Private (PNFP)",
    "ownership": "Private, not-for-profit",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.30417,
    "lng": 32.55278,
    "bedsTotal": 275,
    "bedsAvailable": 95,
    "traumaTotal": 6,
    "traumaAvailable": 3,
    "phone": "+256 414 270 465",
    "country": "Uganda"
  },
  {
    "id": "HOSP-27",
    "name": "Kampala Medical Chambers Hospital",
    "tier": "Private",
    "ownership": "Private, for-profit",
    "region": "Central",
    "zone": "Kampala City Centre",
    "lat": 0.31722,
    "lng": 32.57667,
    "bedsTotal": 60,
    "bedsAvailable": 20,
    "traumaTotal": 3,
    "traumaAvailable": 1,
    "phone": "+256 393 260 100",
    "country": "Uganda"
  },
  {
    "id": "HOSP-EAC-01",
    "name": "Kenyatta National Hospital",
    "tier": "National Referral",
    "ownership": "Public",
    "country": "Kenya",
    "region": "Kenya",
    "zone": "Upper Hill, Nairobi",
    "lat": -1.301,
    "lng": 36.8073,
    "bedsTotal": 1800,
    "bedsAvailable": 520,
    "traumaTotal": 30,
    "traumaAvailable": 12,
    "phone": "+254 20 272 6300"
  },
  {
    "id": "HOSP-EAC-02",
    "name": "Muhimbili National Hospital",
    "tier": "National Referral",
    "ownership": "Public",
    "country": "Tanzania",
    "region": "Tanzania",
    "zone": "Upanga West, Dar es Salaam",
    "lat": -6.80773,
    "lng": 39.27221,
    "bedsTotal": 1500,
    "bedsAvailable": 430,
    "traumaTotal": 25,
    "traumaAvailable": 10,
    "phone": "+255 22 215 0302"
  },
  {
    "id": "HOSP-EAC-03",
    "name": "University Teaching Hospital of Kigali (CHUK)",
    "tier": "National Referral",
    "ownership": "Public",
    "country": "Rwanda",
    "region": "Rwanda",
    "zone": "Kigali",
    "lat": -1.9484,
    "lng": 30.0614,
    "bedsTotal": 500,
    "bedsAvailable": 150,
    "traumaTotal": 15,
    "traumaAvailable": 7,
    "phone": "+250 788 300 300"
  },
  {
    "id": "HOSP-EAC-04",
    "name": "King Faisal Hospital Kigali",
    "tier": "Private/Referral",
    "ownership": "Public-private",
    "country": "Rwanda",
    "region": "Rwanda",
    "zone": "Kigali",
    "lat": -1.9548,
    "lng": 30.0908,
    "bedsTotal": 250,
    "bedsAvailable": 80,
    "traumaTotal": 12,
    "traumaAvailable": 6,
    "phone": "+250 788 309 003"
  },
  {
    "id": "HOSP-EAC-05",
    "name": "Centre Hospitalo-Universitaire de Kamenge (CHUK)",
    "tier": "National Referral",
    "ownership": "Public",
    "country": "Burundi",
    "region": "Burundi",
    "zone": "Bujumbura",
    "lat": -3.35684,
    "lng": 29.38527,
    "bedsTotal": 420,
    "bedsAvailable": 130,
    "traumaTotal": 10,
    "traumaAvailable": 5,
    "phone": "+257 22 21 8149"
  },
  {
    "id": "HOSP-EAC-06",
    "name": "Juba Teaching Hospital",
    "tier": "National Referral",
    "ownership": "Public",
    "country": "South Sudan",
    "region": "South Sudan",
    "zone": "Unity Avenue, Juba",
    "lat": 4.850082,
    "lng": 31.608532,
    "bedsTotal": 512,
    "bedsAvailable": 160,
    "traumaTotal": 12,
    "traumaAvailable": 5,
    "phone": "+211 912 100 100"
  },
  {
    "id": "HOSP-EAC-07",
    "name": "Kinshasa General Hospital (Hôpital Général de Kinshasa)",
    "tier": "National Referral",
    "ownership": "Public",
    "country": "DR Congo",
    "region": "DR Congo",
    "zone": "Gombe, Kinshasa",
    "lat": -4.3246,
    "lng": 15.3122,
    "bedsTotal": 2000,
    "bedsAvailable": 600,
    "traumaTotal": 20,
    "traumaAvailable": 8,
    "phone": "+243 997 235 775"
  },
  {
    "id": "HOSP-EAC-08",
    "name": "Cliniques Universitaires de Kinshasa (CUK)",
    "tier": "National Referral",
    "ownership": "Public",
    "country": "DR Congo",
    "region": "DR Congo",
    "zone": "Lemba, Kinshasa",
    "lat": -4.379,
    "lng": 15.331,
    "bedsTotal": 300,
    "bedsAvailable": 95,
    "traumaTotal": 10,
    "traumaAvailable": 4,
    "phone": "+243 897 235 775"
  }
];

export const INITIAL_EMTS: Emt[] = [
  {
    "id": "EMT-001",
    "name": "Namutebi Sarah",
    "level": "Advanced EMT",
    "certBody": "AAPU (Association of Ambulance Professionals Uganda)",
    "agency": "Uganda Red Cross Society",
    "region": "Central",
    "phone": "+256 772 501 001",
    "status": "On Duty"
  },
  {
    "id": "EMT-002",
    "name": "Okello David",
    "level": "Paramedic",
    "certBody": "AAPU (Association of Ambulance Professionals Uganda)",
    "agency": "Ministry of Health National Ambulance Service",
    "region": "Northern",
    "phone": "+256 772 501 002",
    "status": "On Duty"
  },
  {
    "id": "EMT-003",
    "name": "Nakato Grace",
    "level": "Basic EMT",
    "certBody": "AAPU (Association of Ambulance Professionals Uganda)",
    "agency": "St John Ambulance Uganda",
    "region": "Central",
    "phone": "+256 772 501 003",
    "status": "Off Duty"
  },
  {
    "id": "EMT-004",
    "name": "Byaruhanga Moses",
    "level": "Advanced EMT",
    "certBody": "AAPU (Association of Ambulance Professionals Uganda)",
    "agency": "Ministry of Health National Ambulance Service",
    "region": "Western",
    "phone": "+256 772 501 004",
    "status": "On Duty"
  },
  {
    "id": "EMT-005",
    "name": "Auma Betty",
    "level": "Basic EMT",
    "certBody": "AAPU (Association of Ambulance Professionals Uganda)",
    "agency": "Uganda Red Cross Society",
    "region": "Eastern",
    "phone": "+256 772 501 005",
    "status": "On Duty"
  },
  {
    "id": "EMT-006",
    "name": "Wanyama Peter",
    "level": "Paramedic",
    "certBody": "Uganda Nurses & Midwives Council",
    "agency": "Mulago National Referral Hospital Ambulance Unit",
    "region": "Central",
    "phone": "+256 772 501 006",
    "status": "Off Duty"
  },
  {
    "id": "EMT-007",
    "name": "Kwagala Irene",
    "level": "Advanced EMT",
    "certBody": "AAPU (Association of Ambulance Professionals Uganda)",
    "agency": "Ministry of Health National Ambulance Service",
    "region": "Eastern",
    "phone": "+256 772 501 007",
    "status": "On Duty"
  },
  {
    "id": "EMT-008",
    "name": "Opio Samuel",
    "level": "Basic EMT",
    "certBody": "AAPU (Association of Ambulance Professionals Uganda)",
    "agency": "Ministry of Health National Ambulance Service",
    "region": "Northern",
    "phone": "+256 772 501 008",
    "status": "On Duty"
  },
  {
    "id": "EMT-009",
    "name": "Nabirye Joan",
    "level": "Advanced EMT",
    "certBody": "Allied Health Professionals Council",
    "agency": "Case Medical Centre Ambulance",
    "region": "Central",
    "phone": "+256 772 501 009",
    "status": "On Duty"
  },
  {
    "id": "EMT-010",
    "name": "Tumusiime Allan",
    "level": "Paramedic",
    "certBody": "AAPU (Association of Ambulance Professionals Uganda)",
    "agency": "St John Ambulance Uganda — Kasese Station",
    "region": "Western",
    "phone": "+256 772 501 010",
    "status": "Off Duty"
  }
];
